### ISSUE TITLE
[steps-resource-archive] copies content of previous archive into current archive

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [bitrise-io/steps-resource-archive#12]
I'm using two archive steps right after one another in the same directory.
```
  - resource-archive@2:
      title: archive_step_1
      inputs:
      - extract_to_path: /dir0
      - archive_url: /archive0.zip
  - resource-archive@2:
      title: archive_step_2
      inputs:
      - extract_to_path: /dir1
      - archive_url: /archive1.zip
```

Problem:
The `dir1` contains the content of archive0.zip and archive1.zip.  

I think the issue is due to the fact that the `resource-archive` step extracts to the `unarchived` directory regardless of the contents of the `unarchived` directory, effectively merging the new unarchived content with the previously unarchived content. The contents of the `unarchived` directory are then copied into the `extract_to_path` directory.
